version: 1
ghcr:
  upload: true
  cve-scan: true

registries:

images:
  - directory: "rust/1.75-24.04"
  - directory: "rust/1.85-24.04"
  - directory: "rust/1.85-25.10"
  - directory: "rust/1.88-25.10"
  - directory: "rust/1.93-26.04"
